---
name: Hayaworld Packer VM Image Creation Jobs
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      vmname:
        default: "origin"
        description: 'VM name (overwrite VM if same name VM exists)'
        required: true
      OS_Type:
        description: "Choose OS Type"
        required: true
        default: "server-22.04"
        type: choice
        options:
          - "minimal-22.04"
          - "server-22.04"
          - "minimal-24.10"
      deploy_confirm:
        default: false
        description: "Confirm to build"
        type: boolean

jobs:
  Is_vCSA_Active:
    runs-on: self-hosted
    steps:
      - name: Check if vcsa working
        run: |
          ping -c 2 vcsa.hayaworld.home

  Lint:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        file:
          - "minimal-22.04/minimal-22.04.json"
          - "server-22.04/server-22.04.json"
          - "minimal-24.10/minimal-24.10.json"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Packer Validate
        run: |
          DIRNAME=$(echo ${{ matrix.file }} | awk -F'/' '{print $1}')
          packer validate \
            --var-file=${DIRNAME}/variables.json \
            -var "vcenter_server_password=${{ secrets.VCSA_PASSWORD }}" \
            ${{ matrix.file }}

  Build:
    if: ${{ ( inputs.deploy_confirm == true ) }}
    needs:
      - Lint
      - Is_vCSA_Active
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Show command
        run: |
          echo "packer build \
                  --var-file="${{ inputs.OS_Type }}/variables.json" \
                  -var "vm_name=${{ inputs.vmname }}" \
                  -var "http_directory=${{ inputs.OS_Type }}/http/" \
                  -force \
                  ${{ inputs.OS_Type }}/${{ inputs.OS_Type }}.json"
      
      - name: Run Packer Validate
        run: |
          cd "${{ inputs.OS_Type }}"
          packer build \
            --var-file="variables.json" \
            -var "vcenter_server_password=${{ secrets.VCSA_PASSWORD }}" \
            -var "vm_name=${{ inputs.vmname }}" \
            -force \
            ${{ inputs.OS_Type }}.json
