---
name: Hayaworld Packer VM Image Creation Jobs
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      vmname:
        default: "origin"
        description: 'VM name (overwrite VM if same name VM exists)'
        required: true
      OS_Type:
        description: "Choose OS Type"
        required: true
        default: "server-22.04"
        type: choice
        options:
          - "minimal-22.04"
          - "server-22.04"
      deploy_confirm:
        default: false
        description: "Confirm to build"
        type: boolean

jobs:
  Validate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Packer Validate
        run: |
          packer validate \
            --var-file=./variables.json \
            -var "vcenter_server_password=${{ secrets.VCSA_PASSWORD }}" \
            ubuntu-22.04.json

  Is_vCSA_Active:
    runs-on: self-hosted
    steps:
      - name: Run Packer Validate
        run: |
          ping -c 2 vcsa.hayaworld.home 

  Build:
    if: inputs.deploy_confirm == true
    needs:
      - Validate
      - Is_vCSA_Active
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Packer Validate
        run: |
          packer build \
            --var-file=${{ inputs.OS_Type }}/variables.json \
            -var "vcenter_server_password=${{ secrets.VCSA_PASSWORD }}" \
            -var "vm_name=${{ inputs.vmname }}" \
            -force \
            ${{ inputs.OS_Type }}/${{ inputs.OS_Type }}.json
